### PR TITLE
QOLDEV-1003 add optional testing of latest CKAN master

### PR DESCRIPTION
**Pull request by ThrawnCA**
Add a test run on the latest upstream CKAN master, with success being optional (and tests currently fail), just so we have visibility.

### CODE REVIEW

**Review by duttonw — APPROVED** [review]

**Comment by duttonw** [comment]
hmm, master showing green even with test failures which are not surfaced is a bit :/

```
=========================== short test summary info ============================
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_show_url - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_s3 - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_wrong_filename - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_s3_no_filename - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_url_link - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_url - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download_no_filename - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_s3_resource_mimetype - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_resource_download - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_controller.py::TestS3Controller::test_s3_download_link - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_resource_upload - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_package_update - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_uploader_get_path - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_resource_url_unsigned_for_public_dataset - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_resource_url_signed_for_private_dataset - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_making_dataset_private_updates_object_visibility - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_making_dataset_public_updates_object_visibility - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_non_current_objects_are_private - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_non_current_objects_match_acl - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_non_current_objects_match_auto_acl - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_delete_non_current_objects_after_expiry - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_do_not_delete_non_current_objects_before_expiry - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_assembling_object_metadata_headers - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_encoding_object_metadata_headers - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_ignoring_non_uploads - KeyError: 'id'
FAILED ckanext/s3filestore/tests/test_uploader.py::TestS3ResourceUploader::test_detect_office_document_type - KeyError: 'id'
================= 26 failed, 14 passed, 213 warnings in 46.22s =================
Error: Process completed with exit code 1.
```

**Comment by duttonw** [comment]
i believe we need a way to get the details out if it did 'fail'

can you put   --junitxml=test-results/results.xml  or similar to get an xml version of the tests results

https://github.com/test-summary/action


i.e.

   - name: Test Summary
       if: always()
      uses: test-summary/action@v2
      with:
            paths: "test-results/results.xml"

**Comment by ThrawnCA** [comment]
> i believe we need a way to get the details out if it did 'fail'

How does https://github.com/qld-gov-au/ckanext-s3filestore/actions/runs/11792145642 look?

**Comment by duttonw** [comment]
> > i believe we need a way to get the details out if it did 'fail'
> 
> How does https://github.com/qld-gov-au/ckanext-s3filestore/actions/runs/11792145642 look?

 :D

**Pull request merged**
